# Generated by Django 4.2.9 on 2024-12-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('song_url', models.URLField()),
                ('duration_ms', models.IntegerField()),
                ('valence', models.FloatField()),
                ('energy', models.FloatField()),
                ('added_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Canción Eliminada',
                'verbose_name_plural': 'Canciones Eliminadas',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='SpotifyFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('song_url', models.URLField(unique=True)),
                ('duration_ms', models.IntegerField()),
                ('valence', models.FloatField()),
                ('energy', models.FloatField()),
                ('added_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Canción Favorita',
                'verbose_name_plural': 'Canciones Favoritas',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='SpotifyTopSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('song_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Canción Top',
                'verbose_name_plural': 'Canciones Top',
            },
        ),
    ]
