# Generated by Django 4.2.9 on 2024-12-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedsongs',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='deletedsongs',
            name='valence',
        ),
        migrations.RemoveField(
            model_name='spotifyfavorites',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='spotifyfavorites',
            name='valence',
        ),
    ]
