# Generated by Django 4.2.9 on 2024-12-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_remove_deletedsongs_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedsongs',
            name='album_cover',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='spotifyfavorites',
            name='album_cover',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='spotifytopsongs',
            name='album_cover',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
