# Generated by Django 4.2.9 on 2025-01-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_deletedsongs_album_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedsongs',
            name='preview_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='spotifyfavorites',
            name='preview_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='spotifytopsongs',
            name='preview_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
