# Generated by Django 4.2.9 on 2025-02-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
