# Generated by Django 4.2.9 on 2025-02-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0002_news_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
