# Generated by Django 4.2.9 on 2025-02-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0003_news_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='deleted',
        ),
    ]
