# Generated by Django 4.2.9 on 2025-02-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0004_remove_news_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
