# Generated by Django 4.2.9 on 2025-02-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0005_news_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsource',
            name='deep_search',
            field=models.BooleanField(default=False, help_text='Obtener el contenido completo del artículo desde la URL original', verbose_name='Búsqueda profunda'),
        ),
    ]
