# Generated by Django 4.2.9 on 2025-02-28 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0008_news_embedding_news_is_redundant_news_similar_to_and_more'),
    ]

    operations = [
    ]
