# Generated by Django 4.2.9 on 2025-03-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0009_auto_20250227_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_filtered',
            field=models.BooleanField(default=False, verbose_name='Filtrada automáticamente'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminada por usuario'),
        ),
    ]
