# Generated by Django 4.2.9 on 2025-04-01 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0010_news_is_filtered_alter_news_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterword',
            name='title_only',
            field=models.BooleanField(default=False, help_text='Si está activado, solo filtra noticias donde la palabra aparezca en el título', verbose_name='Solo en título'),
        ),
        migrations.AddField(
            model_name='news',
            name='filtered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filtered_news', to='my_news.filterword', verbose_name='Filtrada por palabra'),
        ),
    ]
