# Generated by Django 4.2.9 on 2025-04-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0011_filterword_title_only_news_filtered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsource',
            name='similarity_threshold',
            field=models.FloatField(default=0.92, help_text='Valor entre 0 y 1 (e.g., 0.92). Noticias con similitud mayor o igual serán marcadas como redundantes.', verbose_name='Umbral de Similitud'),
        ),
    ]
