# Generated by Django 5.0.4 on 2025-04-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0014_aifilterinstruction_news_ai_filter_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_ai_filtered',
            field=models.BooleanField(default=False, verbose_name='Filtro IA'),
        ),
    ]
