# Generated by Django 5.0.4 on 2025-05-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0015_news_is_ai_filtered'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsource',
            name='gemini_model_name',
            field=models.CharField(default='gemini-1.5-flash', help_text="Nombre del modelo de Gemini a utilizar para esta fuente (ej: 'gemini-1.5-flash', 'gemini-pro').", max_length=100, verbose_name='Modelo Gemini'),
        ),
    ]
