# Generated by Django 5.0.4 on 2025-05-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0016_feedsource_gemini_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='gemini-1.5-flash', help_text="Nombre del modelo de Gemini a utilizar globalmente (ej: 'gemini-1.5-flash', 'gemini-pro').", max_length=100, verbose_name='Modelo Gemini Global')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Global Gemini',
                'verbose_name_plural': 'Configuraciones Globales Gemini',
            },
        ),
        migrations.RemoveField(
            model_name='feedsource',
            name='gemini_model_name',
        ),
    ]
