# Generated by Django 5.0.4 on 2025-05-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0017_geminiglobalsetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geminiglobalsetting',
            name='model_name',
            field=models.CharField(default='gemini-2.0-flash', help_text="Nombre del modelo de Gemini a utilizar globalmente (ej: 'gemini-1.5-flash', 'gemini-pro').", max_length=100, verbose_name='Modelo Gemini Global'),
        ),
    ]
