# Generated by Django 5.0.4 on 2025-06-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0019_add_db_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='news',
            name='news_redundancy_idx',
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_redundant', 'is_filtered'], name='news_redundancy_idx'),
        ),
    ]
