# Generated by Django 5.0.4 on 2025-06-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0020_fix_db_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='news',
            name='news_visible_idx',
        ),
        migrations.RemoveIndex(
            model_name='news',
            name='news_source_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='news',
            name='news_redundancy_idx',
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_ai_filtered',
            field=models.BooleanField(default=False, verbose_name='Filtro IA'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminada'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_filtered',
            field=models.BooleanField(default=False, verbose_name='Filtro Aut.'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_redundant',
            field=models.BooleanField(default=False, verbose_name='Redundante'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
