# Generated by Django 5.0.4 on 2025-07-20 00:02

from django.db import migrations, connection


def remove_index_if_exists(apps, schema_editor):
    """Remueve índices solo si existen en la base de datos"""
    cursor = connection.cursor()
    
    # Lista de índices que pueden necesitar ser removidos
    indexes_to_check = [
        'news_visible_idx',
        'news_source_date_idx', 
        'news_redundancy_idx'
    ]
    
    for index_name in indexes_to_check:
        try:
            # Verificar si el índice existe en SQLite
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='index' AND name=?
            """, [index_name])
            
            if cursor.fetchone():
                print(f"Removiendo índice existente: {index_name}")
                cursor.execute(f"DROP INDEX IF EXISTS {index_name}")
            else:
                print(f"Índice {index_name} no existe, saltando...")
                
        except Exception as e:
            print(f"Error al verificar/remover índice {index_name}: {e}")
            # Continuar con el siguiente índice


def reverse_remove_index_if_exists(apps, schema_editor):
    """Operación inversa - no hacer nada ya que los índices fueron removidos intencionalmente"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0021_remove_news_news_visible_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_index_if_exists,
            reverse_remove_index_if_exists,
        ),
    ]
