# Generated by Django 5.0.4 on 2025-09-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0022_fix_missing_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_ai_processed',
            field=models.BooleanField(default=False, verbose_name='Procesada por IA'),
        ),
    ]
