# Generated by Django 5.0.4 on 2025-12-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0023_news_is_ai_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroqGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='llama-3.3-70b-versatile', help_text="Nombre del modelo de Groq a utilizar (ej: 'llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768').", max_length=100, verbose_name='Modelo Groq Global')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Global Groq',
                'verbose_name_plural': 'Configuraciones Globales Groq',
            },
        ),
    ]
