# Generated by Django 5.0.4 on 2026-02-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0024_groqglobalsetting'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_deleted', 'is_filtered', 'is_ai_filtered', 'is_redundant', 'published_date', 'id'], name='news_visible_pub_id_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['created_at', 'id'], name='news_created_id_idx'),
        ),
    ]
