# Generated by Django 5.0.4 on 2026-04-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0026_news_is_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groqglobalsetting',
            name='model_name',
            field=models.CharField(default='qwen/qwen3-32b', help_text="Nombre del modelo de Groq a utilizar (ej: 'qwen/qwen3-32b').", max_length=100, verbose_name='Modelo Groq Global'),
        ),
    ]
