# Generated by Django 5.0.4 on 2026-04-28 18:59

from django.db import migrations, models


def backfill_deleted_at(apps, schema_editor):
    News = apps.get_model('my_news', 'News')
    News.objects.filter(is_deleted=True, deleted_at__isnull=True).update(deleted_at=models.F('created_at'))


def clear_backfilled_deleted_at(apps, schema_editor):
    News = apps.get_model('my_news', 'News')
    News.objects.filter(is_deleted=True, deleted_at=models.F('created_at')).update(deleted_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0027_alter_groqglobalsetting_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eliminada en'),
        ),
        migrations.RunPython(backfill_deleted_at, clear_backfilled_deleted_at),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_deleted', 'deleted_at', 'id'], name='news_deleted_at_idx'),
        ),
    ]
