# Generated by Django 5.0.4 on 2026-06-23

from django.db import migrations, models


OLD_MODEL = 'qwen/qwen3-32b'
NEW_MODEL = 'openai/gpt-oss-120b'


def migrate_deprecated_qwen_model(apps, schema_editor):
    GroqGlobalSetting = apps.get_model('my_news', 'GroqGlobalSetting')
    GroqGlobalSetting.objects.filter(model_name=OLD_MODEL).update(model_name=NEW_MODEL)


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0020_remove_news_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groqglobalsetting',
            name='model_name',
            field=models.CharField(
                default=NEW_MODEL,
                help_text="Nombre del modelo de Groq a utilizar (ej: 'openai/gpt-oss-120b').",
                max_length=100,
                verbose_name='Modelo Groq Global',
            ),
        ),
        migrations.RunPython(migrate_deprecated_qwen_model, migrations.RunPython.noop),
    ]
