# Generated by Codex on 2026-07-01

from django.db import migrations, models


def copy_groq_setting_to_cerebras(apps, schema_editor):
    GroqGlobalSetting = apps.get_model('my_news', 'GroqGlobalSetting')
    CerebrasGlobalSetting = apps.get_model('my_news', 'CerebrasGlobalSetting')
    if CerebrasGlobalSetting.objects.exists():
        return

    groq_setting = GroqGlobalSetting.objects.first()
    model_name = 'gemma-4-31b'
    if groq_setting and groq_setting.model_name == 'gemma-4-31b':
        model_name = groq_setting.model_name
    CerebrasGlobalSetting.objects.create(model_name=model_name)


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0029_migrate_qwen_groq_model_to_gpt_oss_120b'),
    ]

    operations = [
        migrations.CreateModel(
            name='CerebrasGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='gemma-4-31b', help_text="Nombre del modelo de Cerebras a utilizar (ej: 'gemma-4-31b').", max_length=100, verbose_name='Modelo Cerebras Global')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Global Cerebras',
                'verbose_name_plural': 'Configuraciones Globales Cerebras',
            },
        ),
        migrations.RunPython(copy_groq_setting_to_cerebras, migrations.RunPython.noop),
    ]
