# Generated by Django 5.2 on 2026-08-02 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0031_rename_ai_model_setting_drop_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='interest_score',
            field=models.FloatField(blank=True, help_text='Estimación en [-1, 1] a partir de los pulgares. Solo informativa: no filtra nada.', null=True, verbose_name='Interés'),
        ),
        migrations.AddField(
            model_name='news',
            name='user_vote',
            field=models.SmallIntegerField(choices=[(1, 'Me interesa'), (0, 'Sin voto'), (-1, 'No me interesa')], default=0, verbose_name='Voto'),
        ),
        migrations.CreateModel(
            name='NewsFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=500, verbose_name='Titular')),
                ('vote', models.SmallIntegerField(choices=[(1, 'Me interesa'), (-1, 'No me interesa')], verbose_name='Voto')),
                ('vector', models.BinaryField(verbose_name='Embedding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='my_news.news', verbose_name='Noticia')),
            ],
            options={
                'verbose_name': 'Voto de interés',
                'verbose_name_plural': 'Votos de interés',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['vote'], name='newsfeedback_vote_idx')],
            },
        ),
    ]
