# Generated by Django 5.2 on 2026-08-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0032_news_interest_score_news_user_vote_newsfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsource',
            name='similarity_threshold',
            field=models.FloatField(default=0.85, help_text='Valor entre 0 y 1. Noticias con similitud mayor o igual serán marcadas como redundantes. 0.85 es el punto medido sobre el histórico: por encima son duplicados reales y por debajo son noticias distintas. Con 0.92 solo se caza un tercio de los duplicados.', verbose_name='Umbral de Similitud'),
        ),
    ]
