# Generated by Django 5.2 on 2026-08-02 03:09

from django.conf import settings
from django.db import migrations, models


def marcar_modelo_actual(apps, schema_editor):
    """Las etiquetas que ya existen son del modelo configurado ahora mismo.

    Se rellenan explícitamente para que a partir de aquí cualquier fila con un
    valor distinto sea, sin ambigüedad, de otro modelo.
    """
    NewsFeedback = apps.get_model('my_news', 'NewsFeedback')
    actual = getattr(settings, 'GEMINI_EMBEDDING_MODEL', 'gemini-embedding-001')
    NewsFeedback.objects.filter(model_version='').update(model_version=actual)


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0033_alter_feedsource_similarity_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeedback',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Modelo de embeddings'),
        ),
        migrations.RunPython(marcar_modelo_actual, migrations.RunPython.noop),
    ]
