# Generated by Django 5.2 on 2026-08-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0034_newsfeedback_model_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ok', 'Correcta'), ('paused', 'Pausada'), ('error', 'Con error')], default='ok', max_length=10, verbose_name='Estado')),
                ('reason', models.CharField(blank=True, help_text='Resumen corto y legible de por qué se pausó o falló.', max_length=200, verbose_name='Motivo')),
                ('detail', models.TextField(blank=True, help_text='Mensaje técnico del proveedor, para diagnosticar sin abrir el log.', verbose_name='Detalle')),
                ('new_count', models.IntegerField(default=0, verbose_name='Noticias nuevas')),
                ('retry_at', models.DateTimeField(blank=True, help_text='Cuándo se espera que la cuota vuelva, si el proveedor lo indicó.', null=True, verbose_name='Reintento estimado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Estado de la ingesta',
                'verbose_name_plural': 'Estado de la ingesta',
            },
        ),
    ]
