# Generated by Django 5.0.4 on 2026-09-04 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0035_ingestionstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='interest_score',
        ),
        migrations.RemoveField(
            model_name='news',
            name='user_vote',
        ),
        migrations.DeleteModel(
            name='NewsFeedback',
        ),
    ]
