# Generated by Django 5.2 on 2026-09-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0037_migrate_gemma_model_to_qwen'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelsetting',
            name='max_completion_tokens',
            field=models.PositiveIntegerField(blank=True, help_text='Presupuesto de salida por noticia. Vacío usa el valor probado para cada modelo. OJO: el razonamiento se cobra aquí dentro, así que con razonamiento hacen falta 4096 o la respuesta llega truncada y sin JSON, perdiendo la noticia.', null=True, verbose_name='Tokens de respuesta'),
        ),
        migrations.AddField(
            model_name='aimodelsetting',
            name='reasoning_effort',
            field=models.CharField(blank=True, choices=[('', 'Automático (según el modelo)'), ('none', 'Sin razonamiento'), ('low', 'Bajo (recomendado)'), ('medium', 'Medio'), ('high', 'Alto')], default='', help_text="Cuánto razona el modelo antes de responder. 'Automático' usa el valor probado para cada modelo. Medido: 'bajo' no mejora el resumen (que es transcripción) pero estabiliza el short_answer; 'medio' y 'alto' lo empeoran, volviéndolo nulo en titulares que sí esconden el dato.", max_length=10, verbose_name='Razonamiento'),
        ),
    ]
