"""Migra la configuracion de IA de Cerebras a Gemini con Groq de respaldo.

Cerebras dejo de ser viable: su prueba gratuita son 5 dolares que caducan a los
30 dias y no hay plan gratuito, asi que la cuenta acabo dando 402 en todos los
modelos. Gemini y Groq si tienen tier gratuito permanente.

La fila viva se queda apuntando al modelo de Cerebras, que en Gemini no existe,
asi que hay que moverla. Solo se toca si sigue en un modelo de Cerebras: una
eleccion hecha a mano en el admin se respeta.
"""

# Generated by Django 5.2 on 2026-09-09 19:13

from django.db import migrations, models

MODELOS_RETIRADOS = ('qwen-3.8-27b', 'gemma-4-31b', 'zai-glm-4.7')
NUEVO_PROVEEDOR = 'gemini'
NUEVO_MODELO = 'gemini-3.5-flash-lite'
NUEVO_RESPALDO = 'groq'


def migrar_modelo_retirado(apps, schema_editor):
    AIModelSetting = apps.get_model('my_news', 'AIModelSetting')
    AIModelSetting.objects.filter(model_name__in=MODELOS_RETIRADOS).update(
        provider=NUEVO_PROVEEDOR,
        model_name=NUEVO_MODELO,
        fallback_provider=NUEVO_RESPALDO,
    )


def revertir(apps, schema_editor):
    AIModelSetting = apps.get_model('my_news', 'AIModelSetting')
    AIModelSetting.objects.filter(model_name=NUEVO_MODELO).update(model_name=MODELOS_RETIRADOS[0])


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0038_aimodelsetting_reasoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelsetting',
            name='fallback_provider',
            field=models.CharField(blank=True, choices=[('', 'Sin respaldo'), ('gemini', 'Gemini (Google)'), ('groq', 'Groq')], default='groq', help_text='A quién recurrir cuando el principal se queda sin cuota, en vez de pausar la ingesta. Usa su modelo por defecto. Vacío lo desactiva.', max_length=20, verbose_name='Proveedor de respaldo'),
        ),
        migrations.AddField(
            model_name='aimodelsetting',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Gemini (Google)'), ('groq', 'Groq')], default='gemini', help_text='Quién genera los resúmenes. El primero que se intenta.', max_length=20, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='aimodelsetting',
            name='max_completion_tokens',
            field=models.PositiveIntegerField(blank=True, help_text="Presupuesto de salida por noticia en Groq. Vacío usa el valor probado para cada modelo. OJO: el razonamiento se cobra aquí dentro, así que por encima de 'bajo' hacen falta 4096 o la respuesta llega truncada y sin JSON, perdiendo la noticia.", null=True, verbose_name='Tokens de respuesta'),
        ),
        migrations.AlterField(
            model_name='aimodelsetting',
            name='model_name',
            field=models.CharField(blank=True, default='gemini-3.5-flash-lite', help_text="Modelo del proveedor de arriba (ej: 'gemini-3.5-flash-lite'). Vacío usa el modelo por defecto de ese proveedor.", max_length=100, verbose_name='Modelo IA Global'),
        ),
        migrations.AlterField(
            model_name='aimodelsetting',
            name='reasoning_effort',
            field=models.CharField(blank=True, choices=[('', 'Automático (según el modelo)'), ('none', 'Sin razonamiento'), ('low', 'Bajo (recomendado)'), ('medium', 'Medio'), ('high', 'Alto')], default='', help_text="Solo afecta a Groq; Gemini 3.5 Lite no gasta tokens de razonamiento (medido). 'Automático' usa el valor probado de cada modelo. Medido: 'bajo' no mejora el resumen, que es transcripción, pero estabiliza el short_answer; 'medio' y 'alto' lo empeoran, volviéndolo nulo en titulares que sí esconden el dato.", max_length=10, verbose_name='Razonamiento'),
        ),
        migrations.RunPython(migrar_modelo_retirado, revertir),
    ]
