# Generated by Django 5.2 on 2026-09-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0039_aimodelsetting_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelsetting',
            name='thinking_level',
            field=models.CharField(blank=True, choices=[('', 'Por defecto del modelo'), ('MINIMAL', 'Mínimo'), ('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto (el único que piensa en Flash Lite)')], default='', help_text="Solo afecta a Gemini. Medido en gemini-3.5-flash-lite: de los cuatro niveles solo 'Alto' piensa de verdad; los demás dan cero tokens de pensamiento y no cambian nada. 'Alto' cuesta el triple de tokens y ~19 s por noticia en vez de 1,4 s.", max_length=10, verbose_name='Pensamiento (Gemini)'),
        ),
    ]
