# Generated by Django 5.2 on 2026-09-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0040_aimodelsetting_thinking'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='similar_ref',
            field=models.CharField(blank=True, default='', max_length=600, verbose_name='Original (ya purgado)'),
        ),
    ]
