# Generated by Django 5.2 on 2026-09-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0041_news_similar_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsource',
            name='similarity_threshold',
            field=models.FloatField(default=0.9, help_text='Valor entre 0 y 1. Noticias con similitud mayor o igual serán marcadas como redundantes. 0.90 es el punto medido en septiembre de 2026 sobre 651 pares reales: los duplicados de verdad viven de 0.92 para arriba y la franja 0.90-0.92 es mixta, mientras que por debajo de 0.90 lo que hay son noticias distintas del mismo tema (PS5 contra Xbox, Thundermail contra Proton Mail). El 0.85 anterior ocultaba el 28% del feed; con 0.90 es el 10%. Bajarlo de 0.90 no afina la detección: amplía el tema que se considera repetido.', verbose_name='Umbral de Similitud'),
        ),
    ]
