# Generated by Django 5.2 on 2026-09-23 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0042_alter_feedsource_similarity_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_embedding', to='my_news.news')),
            ],
            options={
                'verbose_name': 'Vector pendiente',
                'verbose_name_plural': 'Vectores pendientes',
            },
        ),
    ]
