# Generated by Django 5.2 on 2026-09-23 01:16

from django.db import migrations, models


def todos_solo_en_titulo(apps, schema_editor):
    # No es solo cambiar el valor por defecto: los falsos positivos venían de
    # los filtros ya creados que buscaban también en la descripción.
    FilterWord = apps.get_model('my_news', 'FilterWord')
    FilterWord.objects.filter(title_only=False).update(title_only=True)


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0043_pendingembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterword',
            name='title_only',
            field=models.BooleanField(default=True, help_text='Si está activado, solo filtra noticias donde la palabra aparezca en el título. Buscar también en la descripción da muchos falsos positivos: una mención de pasada basta para ocultar la noticia.', verbose_name='Solo en título'),
        ),
        # Al revertir no se sabe cuáles buscaban en la descripción, así que el
        # dato no se deshace: si hace falta, se reactiva a mano por filtro.
        migrations.RunPython(todos_solo_en_titulo, migrations.RunPython.noop),
    ]
