# Generated by Django 5.0.4 on 2026-07-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trakt_history_id', models.BigIntegerField(unique=True, verbose_name='ID historial Trakt')),
                ('media_type', models.CharField(choices=[('movie', 'Película'), ('episode', 'Episodio')], max_length=10, verbose_name='Tipo')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('episode_title', models.CharField(blank=True, default='', max_length=300, verbose_name='Título episodio')),
                ('season', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Temporada')),
                ('episode', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Episodio')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('overview', models.TextField(blank=True, default='', verbose_name='Sinopsis')),
                ('watched_at', models.DateTimeField(verbose_name='Visto el')),
                ('trakt_id', models.PositiveIntegerField(verbose_name='ID Trakt')),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID TMDB')),
                ('trakt_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visto',
                'verbose_name_plural': 'Vistos',
                'ordering': ['-watched_at'],
                'indexes': [models.Index(fields=['-watched_at'], name='watched_at_idx')],
            },
        ),
    ]
