# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcheditem',
            name='user_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mi calificación'),
        ),
    ]
