# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0002_watcheditem_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcheditem',
            name='public_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Calificación general'),
        ),
    ]
