# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0003_watcheditem_public_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcheditem',
            name='total_episodes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Episodios totales'),
        ),
    ]
