# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0004_watcheditem_total_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcheditem',
            name='available_episodes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Episodios disponibles'),
        ),
    ]
