# Generated by Django 5.2 on 2026-08-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0006_simkl_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='simklsyncstate',
            name='in_progress_ids',
            field=models.TextField(blank=True, default='', verbose_name='En curso'),
        ),
    ]
