# Generated by Django 5.2 on 2026-08-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0007_simklsyncstate_in_progress_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simklsyncstate',
            name='in_progress_ids',
        ),
        migrations.AddField(
            model_name='simklsyncstate',
            name='pending_ids',
            field=models.TextField(blank=True, default='', verbose_name='Con episodios pendientes'),
        ),
    ]
