# Generated by Django 5.2 on 2026-09-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0009_simklsyncstate_entry_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcheditem',
            name='part_poster',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Carátula del arco (Simkl)'),
        ),
        migrations.AddField(
            model_name='watcheditem',
            name='part_title',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Arco (Simkl)'),
        ),
    ]
