# Generated by Django 5.2 on 2026-09-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0010_watcheditem_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcheditem',
            name='source',
            field=models.CharField(choices=[('trakt', 'Trakt'), ('simkl', 'Simkl'), ('manual', 'Manual')], default='simkl', max_length=10, verbose_name='Fuente'),
        ),
    ]
