[Definition]
actionstart = /usr/local/sbin/fail2ban-nginx-map start "<name>" "%(blck_lst_file)s"
actionflush = /usr/local/sbin/fail2ban-nginx-map flush "<name>" "%(blck_lst_file)s"
actionstop = /usr/local/sbin/fail2ban-nginx-map stop "<name>" "%(blck_lst_file)s"
actioncheck =
actionban = /usr/local/sbin/fail2ban-nginx-map add "<name>" "%(blck_lst_file)s" "<ip>"
actionunban = /usr/local/sbin/fail2ban-nginx-map del "<name>" "%(blck_lst_file)s" "<ip>"

[Init]
blck_lst_file = /etc/nginx/blacklisted-ips.map
