# Generated by Django 5.0.4 on 2024-04-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_link', models.URLField()),
                ('my_rating', models.IntegerField()),
                ('public_rating', models.CharField(max_length=20)),
                ('date_read', models.DateField()),
                ('book_link', models.URLField(unique=True)),
            ],
        ),
    ]
