# Generated by Django 4.2.9 on 2025-01-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('cover_link', models.TextField()),
                ('my_rating', models.IntegerField()),
                ('public_rating', models.CharField(max_length=20)),
                ('date_read', models.DateField()),
                ('book_link', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-date_read'],
            },
        ),
        migrations.CreateModel(
            name='DeletedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('cover_link', models.TextField()),
                ('my_rating', models.IntegerField()),
                ('public_rating', models.CharField(max_length=20)),
                ('date_read', models.DateField()),
                ('book_link', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Libro Eliminado',
                'verbose_name_plural': 'Libros Eliminados',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
