# Generated by Django 5.0.4 on 2024-04-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_link',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_link',
            field=models.TextField(),
        ),
    ]
