# Generated by Django 5.0.4 on 2026-02-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deletedbook',
            name='genres',
            field=models.TextField(blank=True, null=True),
        ),
    ]
