# Generated by Django 5.0.4 on 2026-02-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_visitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
