# Generated by Django 5.0.4 on 2026-02-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_visitlog_visitor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
