# Generated by Django 5.0.4 on 2026-02-27 15:57

from django.db import migrations


def backfill_country_code(apps, schema_editor):
    VisitLog = apps.get_model('home_page', 'VisitLog')
    for visit in VisitLog.objects.filter(country_code='').iterator():
        country = (visit.country or '').strip()
        iso2 = ''
        if len(country) == 2 and country.isalpha():
            iso2 = country.upper()
        else:
            parts = country.replace('-', ' ').split()
            if parts and len(parts[0]) == 2 and parts[0].isalpha():
                iso2 = parts[0].upper()
        if iso2:
            visit.country_code = iso2
            visit.save(update_fields=['country_code'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_visitlog_country_code'),
    ]

    operations = [
        migrations.RunPython(backfill_country_code, noop_reverse),
    ]
