# Generated by Django 5.0.4 on 2026-07-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_book_goodreads_date_added_book_goodreads_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_reading',
            field=models.BooleanField(default=False, verbose_name='Leyendo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_read',
            field=models.DateField(blank=True, null=True),
        ),
    ]
