# Generated by Django 5.2 on 2026-08-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_book_is_reading_alter_book_date_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, db_index=True, default='', max_length=45)),
                ('visitor_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seña propia',
                'verbose_name_plural': 'Señas propias',
                'ordering': ['-last_seen'],
                'unique_together': {('ip_address', 'visitor_id')},
            },
        ),
    ]
