# Generated by Django 5.2 on 2026-08-15 20:43

from django.db import migrations, models
from django.db.models import F


def mark_existing_visits_as_seen(apps, schema_editor):
    """Lo de antes ya se miró: la insignia arranca apagada y solo cuenta lo nuevo."""
    VisitLog = apps.get_model('home_page', 'VisitLog')
    VisitLog.objects.filter(seen_at__isnull=True).update(seen_at=F('visited_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_ownersignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(
            mark_existing_visits_as_seen,
            migrations.RunPython.noop,
        ),
    ]
